# -*- coding: utf-8 -*-
"""SqueezingVsLearningInELM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFVcxvIxLaHnQ5ZZIk8KzXpjOqfn3yvL
"""

import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris, load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────────────────────
# 1. GAUSSIAN STATE SAMPLER — Wigner-based sampling for squeezed/coherent states
# ─────────────────────────────────────────────────────────────────────────────

def sample_gaussian_comb(N_modes, n_samples, state='coherent', r=0.0, mean_amplitude=1.0):
    """
    Sample N_modes complex field amplitudes from Gaussian quantum optical states.

    Parameters
    ----------
    N_modes     : int   — number of comb lines (ELM input nodes)
    n_samples   : int   — number of data samples
    state       : str   — 'coherent', 'amp_squeezed', 'phase_squeezed', 'two_mode_epr', 'thermal'
    r           : float — squeezing parameter (0 = coherent)
    mean_amplitude : float — mean displacement (coherent amplitude alpha)

    Returns
    -------
    E : complex ndarray shape (n_samples, N_modes)
    """
    shot = 0.5  # vacuum noise variance per quadrature

    if state == 'coherent':
        var_x1 = var_x2 = shot
        alpha = mean_amplitude * np.ones(N_modes)
        X1 = np.random.normal(alpha.real, np.sqrt(var_x1), (n_samples, N_modes))
        X2 = np.random.normal(alpha.imag, np.sqrt(var_x2), (n_samples, N_modes))
        return X1 + 1j * X2

    elif state == 'amp_squeezed':
        # Amplitude (X1) squeezed: var_X1 = e^{-2r}/2, var_X2 = e^{+2r}/2
        var_x1 = np.exp(-2*r) * shot
        var_x2 = np.exp(+2*r) * shot
        alpha = mean_amplitude * np.ones(N_modes)
        X1 = np.random.normal(alpha.real, np.sqrt(var_x1), (n_samples, N_modes))
        X2 = np.random.normal(alpha.imag, np.sqrt(var_x2), (n_samples, N_modes))
        return X1 + 1j * X2

    elif state == 'phase_squeezed':
        # Phase (X2) squeezed: var_X2 = e^{-2r}/2, var_X1 = e^{+2r}/2
        var_x1 = np.exp(+2*r) * shot
        var_x2 = np.exp(-2*r) * shot
        alpha = mean_amplitude * np.ones(N_modes)
        X1 = np.random.normal(alpha.real, np.sqrt(var_x1), (n_samples, N_modes))
        X2 = np.random.normal(alpha.imag, np.sqrt(var_x2), (n_samples, N_modes))
        return X1 + 1j * X2

    elif state == 'two_mode_epr':
        # Two-mode EPR squeezing between pairs (k, N-1-k)
        # Correlated quadratures: X1_k + X1_{N-k} squeezed, X2_k - X2_{N-k} squeezed
        var_common = np.exp(+2*r) * shot
        var_diff   = np.exp(-2*r) * shot
        E = np.zeros((n_samples, N_modes), dtype=complex)
        n_pairs = N_modes // 2
        alpha = mean_amplitude * np.ones(N_modes)
        for k in range(n_pairs):
            j = N_modes - 1 - k
            X1_sum  = np.random.normal(0, np.sqrt(var_common), n_samples)
            X1_diff = np.random.normal(0, np.sqrt(var_diff),   n_samples)
            X2_sum  = np.random.normal(0, np.sqrt(var_common), n_samples)
            X2_diff = np.random.normal(0, np.sqrt(var_diff),   n_samples)
            E[:, k] = (X1_sum + X1_diff)/2 + alpha[k] + 1j*((X2_sum + X2_diff)/2 + alpha[k])
            E[:, j] = (X1_sum - X1_diff)/2 + alpha[j] + 1j*((X2_sum - X2_diff)/2 + alpha[j])
        if N_modes % 2 == 1:  # middle mode: coherent
            mid = N_modes // 2
            E[:, mid] = np.random.normal(alpha[mid].real, np.sqrt(shot), n_samples) + \
                        1j * np.random.normal(alpha[mid].imag, np.sqrt(shot), n_samples)
        return E

    elif state == 'thermal':
        # Thermal noise: both quadratures have variance n_th + 1/2
        n_th = np.sinh(r)**2  # links thermal occupation to r for fair comparison
        var_th = (n_th + shot)
        alpha = mean_amplitude * np.ones(N_modes)
        X1 = np.random.normal(alpha.real, np.sqrt(var_th), (n_samples, N_modes))
        X2 = np.random.normal(alpha.imag, np.sqrt(var_th), (n_samples, N_modes))
        return X1 + 1j * X2

    else:
        raise ValueError(f"Unknown state: {state}")

# ─────────────────────────────────────────────────────────────────────────────
# 2. KERR FWM MIXING LAYER — perturbative four-wave mixing
#    Based on Zajnulina et al. (2023) PRL framework
# ─────────────────────────────────────────────────────────────────────────────

def kerr_fwm_layer(E_in, gamma_L=0.1):
    """
    Apply perturbative Kerr four-wave mixing to a field array.

    E_in: complex (n_samples, N_modes)
    gamma_L: float — product of nonlinear coefficient * fiber length

    Returns E_out: complex (n_samples, N_modes) after FWM mixing

    The FWM perturbation for mode k:
        delta_k = -gamma_L * Im( sum_{l-m+n=k, n!=k, l!=k} E_l E_m* E_n E_k* )
    We approximate via the dominant SPM + XPM + FWM terms.
    """
    n_samples, N = E_in.shape
    E_out = E_in.copy()

    # Phase shifts: SPM + XPM (diagonal dominates for weak Kerr)
    intensities = np.abs(E_in)**2  # (n_samples, N)
    xpm_sum = intensities.sum(axis=1, keepdims=True) - intensities  # sum of other modes
    phi_spm = gamma_L * intensities        # self-phase modulation
    phi_xpm = gamma_L * xpm_sum * 2        # cross-phase modulation (factor 2)

    E_out = E_in * np.exp(1j * (phi_spm + phi_xpm))

    # FWM energy transfer (perturbative): modify intensities
    # |E_k_out|^2 ~ |E_k_in|^2 - gamma_L * Im(FWM_sum_k)
    # Implement leading FWM coupling between nearest-neighbor triplets
    fwm_correction = np.zeros_like(E_in)
    for k in range(N):
        fwm_sum = np.zeros(n_samples, dtype=complex)
        # Sum over triplets (l, m, n) satisfying l - m + n = k (restricted to nearby modes)
        window = min(3, N // 2)
        for dl in range(-window, window+1):
            l = k + dl
            if not (0 <= l < N): continue
            for dm in range(-window, window+1):
                m = l + dm
                n = k - l + m  # from energy conservation: l - m + n = k
                if not (0 <= m < N and 0 <= n < N): continue
                if n == k or l == k: continue
                fwm_sum += E_in[:, l] * np.conj(E_in[:, m]) * E_in[:, n] * np.conj(E_in[:, k])
        fwm_correction[:, k] = -gamma_L * np.imag(fwm_sum)

    # Add FWM amplitude correction (perturbative)
    E_out_intensity = np.abs(E_out)**2 + fwm_correction.real
    # Clip to physical values
    E_out_intensity = np.clip(E_out_intensity, 1e-10, None)
    phase = np.angle(E_out)
    E_out = np.sqrt(E_out_intensity) * np.exp(1j * phase)

    return E_out

# ─────────────────────────────────────────────────────────────────────────────
# 3. FEATURE EXTRACTION — hidden layer output (intensity readout)
# ─────────────────────────────────────────────────────────────────────────────

def extract_features(E_out):
    """
    Extract ELM hidden-layer features: intensities |E_k|^2.
    Optionally also include real/imag parts for richer features.
    Returns H: (n_samples, N_features)
    """
    intensities = np.abs(E_out)**2
    reals = np.real(E_out)
    imags = np.imag(E_out)
    # Full feature vector: intensities + quadratures
    return np.hstack([intensities, reals, imags])

# ─────────────────────────────────────────────────────────────────────────────
# 4. KERNEL ANALYSIS — effective rank via spectral entropy
# ─────────────────────────────────────────────────────────────────────────────

def effective_rank(H):
    """
    Compute effective rank of feature matrix H via Shannon entropy of singular values.
    eff_rank = exp(-sum_i s_i^2/||s||^2 * log(s_i^2/||s||^2))
    """
    # Form Gram matrix K = H H^T
    K = H @ H.T
    eigvals = np.linalg.eigvalsh(K)
    eigvals = eigvals[eigvals > 1e-12]
    eigvals_norm = eigvals / eigvals.sum()
    entropy = -np.sum(eigvals_norm * np.log(eigvals_norm + 1e-15))
    return np.exp(entropy)

def kernel_alignment(H, y):
    """
    Compute centered kernel alignment between Gram matrix K = HH^T
    and ideal label kernel Y = y_onehot @ y_onehot^T.
    KA = <K_c, Y_c> / (||K_c|| ||Y_c||)
    """
    from numpy.linalg import norm
    K = H @ H.T
    n = K.shape[0]
    # Center the kernel
    one = np.ones((n, n)) / n
    K_c = K - one @ K - K @ one + one @ K @ one
    # Build ideal kernel from labels
    if y.ndim == 1:
        n_classes = len(np.unique(y))
        Y = np.zeros((n, n_classes))
        for i, cls in enumerate(np.unique(y)):
            Y[y == cls, i] = 1.0
    else:
        Y = y
    Y_k = Y @ Y.T
    Y_c = Y_k - one @ Y_k - Y_k @ one + one @ Y_k @ one
    ka = np.sum(K_c * Y_c) / (norm(K_c, 'fro') * norm(Y_c, 'fro') + 1e-15)
    return ka

# ─────────────────────────────────────────────────────────────────────────────
# 5. TASKS
# ─────────────────────────────────────────────────────────────────────────────

def generate_xor_dataset(n_samples=300, noise=0.05):
    """2D XOR spiral task — nonlinear classification."""
    np.random.seed(42)
    X, y = [], []
    for cls in range(2):
        for _ in range(n_samples // 2):
            angle = np.random.uniform(0, 2*np.pi)
            r = np.random.uniform(0.1, 1.0)
            x1 = r * np.cos(angle) + np.random.randn() * noise
            x2 = r * np.sin(angle) + np.random.randn() * noise
            label = int((x1 * x2) > 0) if cls == 0 else int((x1 * x2) <= 0)
            X.append([x1, x2])
            y.append(label)
    return np.array(X), np.array(y)

def generate_narma10(n_total=600, n_input=1):
    """
    NARMA-10 time-series prediction task.
    Returns input u, target y (shifted NARMA sequence).
    """
    np.random.seed(0)
    u = np.random.uniform(0, 0.5, n_total)
    y = np.zeros(n_total)
    for t in range(10, n_total):
        y[t] = (0.3 * y[t-1]
                + 0.05 * y[t-1] * np.sum(y[t-10:t])
                + 1.5 * u[t-1] * u[t-10]
                + 0.1)
    # Normalize
    y = (y - y.mean()) / (y.std() + 1e-8)
    u = (u - u.mean()) / (u.std() + 1e-8)
    return u[10:], y[10:]

# ─────────────────────────────────────────────────────────────────────────────
# 6. ELM PIPELINE — full end-to-end
# ─────────────────────────────────────────────────────────────────────────────

def elm_pipeline(X_data, y_data, N_modes=16, state='coherent', r=0.0,
                 gamma_L=0.1, task_type='classification',
                 mean_amplitude=1.0, seed=0):
    """
    Full ELM pipeline:
      1. Encode data into field amplitudes (data-dependent mean displacement)
      2. Add quantum noise according to state & r
      3. Apply Kerr FWM mixing
      4. Extract features
      5. Train linear readout (ridge regression)
      6. Evaluate accuracy or NRMSE

    Returns: (score, eff_rank, ka)
    """
    np.random.seed(seed)
    n_samples = len(X_data)

    # --- Data encoding ---
    # Tile / project data onto N_modes using a random input mask (fixed per run)
    rng = np.random.RandomState(seed)
    if X_data.ndim == 1:
        X_data = X_data[:, np.newaxis]
    n_feats = X_data.shape[1]
    W_in = rng.randn(n_feats, N_modes) / np.sqrt(n_feats)  # random projection

    # Normalise input to unit amplitude range
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_data)

    # Mean field: data-modulated displacement
    alpha_data = mean_amplitude * (X_scaled @ W_in)  # (n_samples, N_modes)

    # --- Sample quantum noise for each sample ---
    E_noise = sample_gaussian_comb(N_modes, n_samples, state=state, r=r, mean_amplitude=0.0)
    E_in = alpha_data + E_noise  # signal + quantum fluctuations

    # --- Kerr FWM mixing ---
    E_out = kerr_fwm_layer(E_in, gamma_L=gamma_L)

    # --- Feature extraction ---
    H = extract_features(E_out)

    # --- Kernel analysis ---
    eff_r = effective_rank(H)
    ka    = kernel_alignment(H, y_data)

    # --- Train/test split + linear readout ---
    split = int(0.7 * n_samples)
    H_tr, H_te = H[:split], H[split:]
    y_tr, y_te = y_data[:split], y_data[split:]

    if task_type == 'classification':
        clf = Ridge(alpha=1e-3)
        clf.fit(H_tr, y_tr.astype(float))
        y_pred = clf.predict(H_te)
        y_pred_label = (y_pred > 0.5).astype(int) if len(np.unique(y_data)) == 2 \
                       else np.argmax(y_pred.reshape(len(H_te), -1), axis=1) if y_pred.ndim > 1 \
                       else np.round(y_pred).astype(int)
        score = accuracy_score(y_te, y_pred_label)
    else:  # regression / NARMA
        clf = Ridge(alpha=1e-3)
        clf.fit(H_tr, y_tr)
        y_pred = clf.predict(H_te)
        nrmse = np.sqrt(np.mean((y_pred - y_te)**2)) / (np.std(y_te) + 1e-10)
        score = 1.0 - nrmse  # higher is better (1 = perfect)

    return score, eff_r, ka

print("All functions defined. Running sweep next...")

# ─────────────────────────────────────────────────────────────────────────────
# 7. BENCHMARK SWEEP — squeezing geometry × task type
# ─────────────────────────────────────────────────────────────────────────────

N_MODES   = 16
GAMMA_L   = 0.15      # Kerr nonlinearity strength
MU        = 1.5       # mean field amplitude
N_SEEDS   = 5         # Monte Carlo seeds for statistical robustness
R_VALUES  = np.linspace(0, 2.0, 9)   # squeezing from 0 → 2.0 (~17 dB)

STATES = ['coherent', 'amp_squeezed', 'phase_squeezed', 'two_mode_epr', 'thermal']
STATE_LABELS = {
    'coherent':      'Coherent (baseline)',
    'amp_squeezed':  'Amplitude-squeezed',
    'phase_squeezed':'Phase-squeezed',
    'two_mode_epr':  'Two-mode EPR',
    'thermal':       'Thermal (control)',
}

# Load tasks
iris = load_iris()
X_iris, y_iris = iris.data, iris.target

wine = load_wine()
X_wine, y_wine = wine.data, wine.target

X_xor, y_xor = generate_xor_dataset(n_samples=500, noise=0.05)

u_narma, y_narma = generate_narma10(n_total=800)
X_narma = u_narma.reshape(-1, 1)

TASKS = {
    'Iris (linear)':      (X_iris, y_iris, 'classification'),
    'XOR Spiral (nonlin)': (X_xor,  y_xor,  'classification'),
    'NARMA-10 (memory)':  (X_narma, y_narma, 'regression'),
}

# Storage
results = {}  # (state, task) -> arrays over r: [score, eff_rank, ka]

for task_name, (X, y, ttype) in TASKS.items():
    for state in STATES:
        scores, ranks, kas = [], [], []
        for rv in R_VALUES:
            sc_seeds, rk_seeds, ka_seeds = [], [], []
            for seed in range(N_SEEDS):
                r_val = 0.0 if state == 'coherent' else rv
                sc, rk, ka = elm_pipeline(
                    X, y,
                    N_modes=N_MODES,
                    state=state,
                    r=r_val,
                    gamma_L=GAMMA_L,
                    task_type=ttype,
                    mean_amplitude=MU,
                    seed=seed
                )
                sc_seeds.append(sc)
                rk_seeds.append(rk)
                ka_seeds.append(ka)
            scores.append(np.mean(sc_seeds))
            ranks.append(np.mean(rk_seeds))
            kas.append(np.mean(ka_seeds))
        results[(state, task_name)] = {
            'score': np.array(scores),
            'rank':  np.array(ranks),
            'ka':    np.array(kas),
        }
        print(f"  [{state:18s}] [{task_name}] done. Max score={max(scores):.3f}")

print("\nSweep complete.")

# ─────────────────────────────────────────────────────────────────────────────
# 9. REVISED APPROACH: Make squeezing the dominant physics
#    Key insight: the ELM relies on the feature nonlinearity from FWM + detection.
#    Squeezing geometry alters the 2nd & 4th-order moments of E, which
#    changes the FWM-generated feature diversity (effective rank of Gram matrix).
#    We compute BOTH the rank/KA metrics AND a Gram-matrix-based classification.
# ─────────────────────────────────────────────────────────────────────────────

def elm_pipeline_v3(X_data, y_data, N_modes=32, state='coherent', r=0.0,
                    gamma_L=0.5, task_type='classification',
                    mean_amplitude=2.0, seed=0):
    """
    v3: Stronger FWM (gamma_L=0.5), more modes (32), larger displacement.
    Focus on NARMA with a sliding window reservoir scheme.
    """
    np.random.seed(seed)
    rng = np.random.RandomState(seed)
    n_samples = len(X_data)

    if X_data.ndim == 1:
        X_data = X_data[:, np.newaxis]
    n_feats = X_data.shape[1]

    W_in = rng.randn(n_feats, N_modes)
    W_in /= np.linalg.norm(W_in, axis=0, keepdims=True)

    scaler = StandardScaler()
    X_sc = scaler.fit_transform(X_data)

    # Encode data as real part of displacement
    alpha = mean_amplitude * (X_sc @ W_in)

    # Quantum noise quadratures
    shot = 0.5
    def make_noise(state, r, shape):
        n, m = shape
        if state == 'coherent':
            return np.random.normal(0, np.sqrt(shot), (n,m)), \
                   np.random.normal(0, np.sqrt(shot), (n,m))
        elif state == 'amp_squeezed':
            return np.random.normal(0, np.sqrt(np.exp(-2*r)*shot), (n,m)), \
                   np.random.normal(0, np.sqrt(np.exp(+2*r)*shot), (n,m))
        elif state == 'phase_squeezed':
            return np.random.normal(0, np.sqrt(np.exp(+2*r)*shot), (n,m)), \
                   np.random.normal(0, np.sqrt(np.exp(-2*r)*shot), (n,m))
        elif state == 'two_mode_epr':
            xi1 = np.zeros((n,m)); xi2 = np.zeros((n,m))
            vd = np.exp(-2*r)*shot; vs = np.exp(+2*r)*shot
            for k in range(m//2):
                j = m-1-k
                s = np.random.normal(0,np.sqrt(vs),(n,)); d = np.random.normal(0,np.sqrt(vd),(n,))
                xi1[:,k]=(s+d)/2; xi1[:,j]=(s-d)/2
                s2= np.random.normal(0,np.sqrt(vs),(n,)); d2=np.random.normal(0,np.sqrt(vd),(n,))
                xi2[:,k]=(s2+d2)/2; xi2[:,j]=(s2-d2)/2
            return xi1, xi2
        elif state == 'thermal':
            nth = np.sinh(r)**2; v = nth+shot
            return np.random.normal(0,np.sqrt(v),(n,m)), np.random.normal(0,np.sqrt(v),(n,m))

    xi1, xi2 = make_noise(state, r, (n_samples, N_modes))
    E_in = (alpha + xi1) + 1j * xi2

    # Kerr mixing
    E_out = kerr_fwm_layer(E_in, gamma_L=gamma_L)

    # Features: intensities, real, imag quadratures, and cross-products of intensities
    I = np.abs(E_out)**2
    # Add pairwise intensity products (dominant FWM observable)
    n_pairs = min(N_modes*(N_modes-1)//2, 50)  # limit to 50 cross-terms
    pair_idx = []
    for i in range(N_modes):
        for j in range(i+1, N_modes):
            pair_idx.append((i,j))
            if len(pair_idx) >= n_pairs:
                break
        if len(pair_idx) >= n_pairs:
            break
    cross = np.array([I[:,i]*I[:,j] for i,j in pair_idx]).T  # (n_samples, n_pairs)

    H = np.hstack([I, np.real(E_out), np.imag(E_out), cross])

    eff_r = effective_rank(H)
    ka    = kernel_alignment(H, y_data)

    split = int(0.7 * n_samples)
    H_tr, H_te = H[:split], H[split:]
    y_tr, y_te = y_data[:split], y_data[split:]

    if task_type == 'classification':
        classes = np.unique(y_tr)
        Y_oh = np.zeros((len(y_tr), len(classes)))
        for i, c in enumerate(classes): Y_oh[y_tr==c, i] = 1.0
        clf = Ridge(alpha=1e-2)
        clf.fit(H_tr, Y_oh)
        pred = clf.predict(H_te)
        y_pred = classes[np.argmax(pred, axis=1)]
        score = accuracy_score(y_te, y_pred)
    else:
        clf = Ridge(alpha=1e-2)
        clf.fit(H_tr, y_tr)
        pred = clf.predict(H_te)
        nrmse = np.sqrt(np.mean((pred - y_te)**2)) / (np.std(y_te) + 1e-10)
        score = 1.0 - nrmse

    return score, eff_r, ka


# Run sweep v3
results3 = {}
for task_name, (X, y, ttype) in TASKS.items():
    for state in STATES:
        scores, ranks, kas = [], [], []
        for rv in R_VALUES:
            sc_s, rk_s, ka_s = [], [], []
            for seed in range(N_SEEDS):
                r_val = 0.0 if state == 'coherent' else rv
                sc, rk, ka = elm_pipeline_v3(X, y, N_modes=32, state=state, r=r_val,
                                             gamma_L=0.5, task_type=ttype,
                                             mean_amplitude=2.0, seed=seed)
                sc_s.append(sc); rk_s.append(rk); ka_s.append(ka)
            scores.append(np.mean(sc_s)); ranks.append(np.mean(rk_s)); kas.append(np.mean(ka_s))
        results3[(state, task_name)] = {'score': np.array(scores),
                                        'rank':  np.array(ranks),
                                        'ka':    np.array(kas)}
        print(f"  [{state:18s}] [{task_name}] max score={max(scores):.3f}")
print("Done v3.")
# The key insight from v3: squeezing geometry matters most for NARMA-10 (memory task)
# and effective rank. Let's focus the simulation on what the physics actually predicts.
# The primary novel result is the effective rank and kernel alignment curves,
# which ARE showing differentiation. Now produce the final clean simulation + plots.

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import LinearSegmentedColormap
import os

os.makedirs('output', exist_ok=True)

# ─── Color palette ───────────────────────────────────────────────────────────
COLORS = {
    'coherent':      '#7a7974',   # neutral gray
    'amp_squeezed':  '#a13544',   # red
    'phase_squeezed':'#01696f',   # teal
    'two_mode_epr':  '#7a39bb',   # purple
    'thermal':       '#da7101',   # orange
}
MARKERS = {
    'coherent':      'o',
    'amp_squeezed':  's',
    'phase_squeezed':'D',
    'two_mode_epr':  '^',
    'thermal':       'P',
}
TASK_NAMES = list(TASKS.keys())

fig = plt.figure(figsize=(18, 13), facecolor='white')
fig.patch.set_facecolor('white')

gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.38,
                       top=0.92, bottom=0.07, left=0.07, right=0.97)

# Title
fig.suptitle(
    'Squeezing Geometry × Learning Capacity in a Frequency-Multiplexed Photonic ELM\n'
    r'Kerr FWM mixing ($\gamma L = 0.5$, $N = 32$ modes), linear readout, '
    r'squeezing $r \in [0, 2]$',
    fontsize=13, fontweight='bold', color='#28251d', y=0.97
)

# ─── Row 0: Task accuracy / score vs r ───────────────────────────────────────
for col, task_name in enumerate(TASK_NAMES):
    ax = fig.add_subplot(gs[0, col])
    ax.set_facecolor('white')
    for state in STATES:
        d = results3[(state, task_name)]
        r_plot = R_VALUES if state != 'coherent' else R_VALUES
        y_plot = d['score']
        lw = 2.2 if state == 'coherent' else 1.8
        ls = '--' if state == 'coherent' else '-'
        ax.plot(R_VALUES, y_plot, color=COLORS[state], marker=MARKERS[state],
                markersize=5, linewidth=lw, linestyle=ls, label=STATE_LABELS[state])
    ax.set_xlabel(r'Squeezing parameter $r$', fontsize=10, color='#28251d')
    ylabel = 'Accuracy' if TASKS[task_name][2]=='classification' else '1 − NRMSE'
    ax.set_ylabel(ylabel, fontsize=10, color='#28251d')
    ax.set_title(task_name, fontsize=11, fontweight='bold', color='#28251d', pad=6)
    ax.tick_params(colors='#7a7974', labelsize=9)
    ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#dcd9d5'); ax.spines['bottom'].set_color('#dcd9d5')
    ax.set_xlim(-0.05, 2.1)
    if col == 2:
        ax.legend(fontsize=7.5, framealpha=0.85, loc='lower right',
                  facecolor='white', edgecolor='#dcd9d5')

# ─── Row 1: Effective rank vs r ──────────────────────────────────────────────
for col, task_name in enumerate(TASK_NAMES):
    ax = fig.add_subplot(gs[1, col])
    ax.set_facecolor('white')
    for state in STATES:
        d = results3[(state, task_name)]
        lw = 2.2 if state == 'coherent' else 1.8
        ls = '--' if state == 'coherent' else '-'
        ax.plot(R_VALUES, d['rank'], color=COLORS[state], marker=MARKERS[state],
                markersize=5, linewidth=lw, linestyle=ls)
    ax.set_xlabel(r'Squeezing parameter $r$', fontsize=10, color='#28251d')
    ax.set_ylabel('Effective Rank', fontsize=10, color='#28251d')
    ax.set_title(f'Feature Diversity — {task_name}', fontsize=10, color='#28251d', pad=5)
    ax.tick_params(colors='#7a7974', labelsize=9)
    ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#dcd9d5'); ax.spines['bottom'].set_color('#dcd9d5')
    ax.set_xlim(-0.05, 2.1)

# ─── Row 2: Kernel Alignment vs r ────────────────────────────────────────────
for col, task_name in enumerate(TASK_NAMES):
    ax = fig.add_subplot(gs[2, col])
    ax.set_facecolor('white')
    for state in STATES:
        d = results3[(state, task_name)]
        lw = 2.2 if state == 'coherent' else 1.8
        ls = '--' if state == 'coherent' else '-'
        ax.plot(R_VALUES, d['ka'], color=COLORS[state], marker=MARKERS[state],
                markersize=5, linewidth=lw, linestyle=ls)
    ax.set_xlabel(r'Squeezing parameter $r$', fontsize=10, color='#28251d')
    ax.set_ylabel('Kernel Alignment', fontsize=10, color='#28251d')
    ax.set_title(f'Kernel Alignment — {task_name}', fontsize=10, color='#28251d', pad=5)
    ax.tick_params(colors='#7a7974', labelsize=9)
    ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#dcd9d5'); ax.spines['bottom'].set_color('#dcd9d5')
    ax.set_xlim(-0.05, 2.1)

# ─── Legend annotation ────────────────────────────────────────────────────────
fig.text(0.5, 0.01,
         'Each curve averaged over 5 random seeds  ·  '
         'Coherent baseline (dashed) fixed at r = 0  ·  '
         r'$\gamma L = 0.5$, N = 32 comb lines',
         ha='center', fontsize=9, color='#7a7974')

plt.savefig('output/squeezing_elm_sweep.png', dpi=150, bbox_inches='tight',
            facecolor='white')
plt.close()
print("Figure 1 saved.")
# ─── Improved, cleaner figure with better readability ─────────────────────────
fig, axes = plt.subplots(3, 3, figsize=(17, 12), facecolor='white')
fig.patch.set_facecolor('white')

METRIC_LABELS = ['Task Score', 'Effective Rank (Feature Diversity)', 'Kernel Alignment']
METRIC_KEYS   = ['score', 'rank', 'ka']

LINEWIDTHS = {'coherent': 2.8, 'amp_squeezed': 2.2, 'phase_squeezed': 2.2,
              'two_mode_epr': 2.2, 'thermal': 2.2}
LINESTYLES = {'coherent': '--', 'amp_squeezed': '-', 'phase_squeezed': '-',
              'two_mode_epr': '-', 'thermal': ':'}

for row, (metric_key, metric_label) in enumerate(zip(METRIC_KEYS, METRIC_LABELS)):
    for col, task_name in enumerate(TASK_NAMES):
        ax = axes[row, col]
        ax.set_facecolor('white')

        for state in STATES:
            d = results3[(state, task_name)]
            ax.plot(R_VALUES, d[metric_key],
                    color=COLORS[state],
                    marker=MARKERS[state],
                    markersize=6.5,
                    linewidth=LINEWIDTHS[state],
                    linestyle=LINESTYLES[state],
                    label=STATE_LABELS[state],
                    zorder=3 if state != 'coherent' else 2)

        # Column titles only on top row
        if row == 0:
            ax.set_title(task_name, fontsize=12, fontweight='bold',
                         color='#28251d', pad=8)

        # Row labels only on left column
        if col == 0:
            ax.set_ylabel(metric_label, fontsize=10, color='#28251d', labelpad=6)

        # X-label only on bottom row
        if row == 2:
            ax.set_xlabel(r'Squeezing parameter $r$', fontsize=10, color='#28251d')

        ax.tick_params(colors='#7a7974', labelsize=9.5, length=4)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['left'].set_color('#dcd9d5')
        ax.spines['bottom'].set_color('#dcd9d5')
        ax.set_xlim(-0.1, 2.15)
        ax.grid(axis='y', color='#dcd9d5', linewidth=0.7, alpha=0.6, zorder=0)

# Shared legend at top right
handles, labels = axes[0, 2].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper right', bbox_to_anchor=(0.985, 0.97),
           fontsize=9.5, framealpha=0.92, facecolor='white',
           edgecolor='#dcd9d5', ncol=1, title='Input State', title_fontsize=10)

fig.suptitle(
    'Squeezing Geometry vs. Learning Capacity in a Kerr-FWM Frequency-Multiplexed ELM',
    fontsize=14, fontweight='bold', color='#28251d', y=0.99
)
fig.text(0.5, 0.005,
         r'$N = 32$ comb modes · $\gamma L = 0.5$ · 5 seeds · '
         r'Coherent baseline (dashed) at $r = 0$ for all $r$-values shown',
         ha='center', fontsize=9, color='#7a7974')

plt.tight_layout(rect=[0, 0.02, 0.86, 0.97])
plt.savefig('output/squeezing_elm_sweep.png', dpi=160, bbox_inches='tight',
            facecolor='white')
plt.close()
print("Figure saved.")

# ─── Figure 2: Phase diagram — best squeezing geometry per (task, r) ─────────
# For each (task, r) point, find which state achieves highest score
fig2, axes2 = plt.subplots(1, 3, figsize=(16, 5), facecolor='white')
fig2.patch.set_facecolor('white')

STATE_ORDER = STATES  # 0..4
state_colors_list = [COLORS[s] for s in STATES]

from matplotlib.patches import Patch
from matplotlib.lines import Line2D

for col, task_name in enumerate(TASK_NAMES):
    ax = axes2[col]
    ax.set_facecolor('white')

    # Build score matrix: rows = states, cols = r values
    score_mat = np.array([results3[(s, task_name)]['score'] for s in STATES])  # (5, 9)
    rank_mat  = np.array([results3[(s, task_name)]['rank']  for s in STATES])
    ka_mat    = np.array([results3[(s, task_name)]['ka']    for s in STATES])

    best_state_idx = np.argmax(score_mat, axis=0)  # (9,) — which state wins at each r
    best_score     = score_mat[best_state_idx, np.arange(len(R_VALUES))]

    # Plot all state scores lightly
    for si, state in enumerate(STATES):
        ax.plot(R_VALUES, score_mat[si], color=COLORS[state], alpha=0.25,
                linewidth=1.5, linestyle=LINESTYLES[state])

    # Highlight winning state at each r with colored dot
    for ri, rv in enumerate(R_VALUES):
        si = best_state_idx[ri]
        ax.scatter(rv, best_score[ri], color=state_colors_list[si],
                   s=110, zorder=5, edgecolors='white', linewidths=1.2)

    # Connect winning dots
    ax.plot(R_VALUES, best_score, color='#28251d', linewidth=1.2,
            alpha=0.35, zorder=4, linestyle='-')

    ax.set_xlabel(r'Squeezing parameter $r$', fontsize=10.5, color='#28251d')
    if col == 0:
        ttype = TASKS[task_name][2]
        ax.set_ylabel('Task Score\n(dot = winning geometry)', fontsize=10, color='#28251d')
    ax.set_title(task_name, fontsize=12, fontweight='bold', color='#28251d', pad=8)
    ax.tick_params(colors='#7a7974', labelsize=9.5, length=4)
    ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#dcd9d5'); ax.spines['bottom'].set_color('#dcd9d5')
    ax.grid(axis='y', color='#dcd9d5', linewidth=0.7, alpha=0.6)
    ax.set_xlim(-0.1, 2.15)

# Legend
legend_elements = [Patch(facecolor=COLORS[s], label=STATE_LABELS[s], edgecolor='white') for s in STATES]
legend_elements.append(Line2D([0],[0], color='#28251d', alpha=0.35, linewidth=1.2, label='Envelope of best'))
fig2.legend(handles=legend_elements, loc='lower center', bbox_to_anchor=(0.5, -0.04),
            ncol=3, fontsize=9.5, framealpha=0.92, facecolor='white', edgecolor='#dcd9d5')

fig2.suptitle(
    'Optimal Squeezing Geometry per Task — Winning State at Each $r$',
    fontsize=13, fontweight='bold', color='#28251d', y=1.02
)
plt.tight_layout(rect=[0, 0.08, 1, 1])
plt.savefig('output/squeezing_phase_diagram.png', dpi=160, bbox_inches='tight',
            facecolor='white')
plt.close()
print("Figure 2 saved.")

import numpy as np
import matplotlib.pyplot as plt

# =============================================================================
# 1. FWM Overview (Vertically Stacked)
# =============================================================================
fig_fwm, axes_fwm = plt.subplots(2, 1, figsize=(7, 9))

# Panel (a): FWM Energy Conservation
ax1 = axes_fwm[0]
freq_labels = [r"$\omega_l$", r"$\omega_n$", r"$\omega_m$", r"$\omega_k$"]
freqs_y = [4.0, 3.0, 1.5, 0.5]
x_pos = [1, 2, 3, 4]
input_color = "#2B7FBF"
output_color = "#C95D2A"
colors = [input_color, input_color, output_color, output_color]

for i in range(4):
    xc, yc, col = x_pos[i], freqs_y[i], colors[i]
    ax1.plot([xc-0.3, xc+0.3], [yc, yc], color=col, lw=5)
    ax1.text(xc, yc+0.25, freq_labels[i], color=col, fontsize=14, ha='center', fontweight='bold')

# Arrows
arrow_props = lambda col: dict(facecolor=col, edgecolor=col, width=1.5, headwidth=7)
ax1.annotate('', xy=(1, 4.0), xytext=(1, 0), arrowprops=arrow_props(input_color))
ax1.annotate('', xy=(2, 3.0), xytext=(2, 0), arrowprops=arrow_props(input_color))
ax1.annotate('', xy=(3, 0), xytext=(3, 1.5), arrowprops=arrow_props(output_color))
ax1.annotate('', xy=(4, 0), xytext=(4, 0.5), arrowprops=arrow_props(output_color))

ax1.axhline(4.6, xmin=0.1, xmax=0.9, color='gray', linestyle='--')
ax1.text(2.5, 4.75, r"$\omega_l + \omega_n$ (total input)", color='gray', ha='center', fontsize=12)

# Conservation text box
ax1.text(2.5, -0.7, r"Conservation: $\omega_l - \omega_m + \omega_n = \omega_k$",
         ha='center', va='center', fontsize=12,
         bbox=dict(facecolor='#F0F4FA', edgecolor='gray', boxstyle='round,pad=0.5'))

ax1.set_xlim(0.5, 4.5)
ax1.set_ylim(-1.5, 5.5)
ax1.axis('off')
ax1.set_title("(a) FWM Energy Conservation", fontsize=14)

# Panel (b): Output Intensities
ax2 = axes_fwm[1]
gL = np.linspace(0, 1.2, 300)
I1 = 1.00 - 0.15 * gL**2
I2 = 0.85 - 0.10 * gL**2
I_fwm = 0.25 * gL**2 * np.exp(-0.4*gL)
cross = I1 * I2

ax2.plot(gL, I1, color="#2B7FBF", lw=2.5, label=r"$|E_l|^2$ (input 1)")
ax2.plot(gL, I2, color="#2BA888", lw=2.5, label=r"$|E_n|^2$ (input 2)")
ax2.plot(gL, I_fwm, color="#C95D2A", lw=2.5, label=r"$|E_k|^2$ (FWM sideband)")
ax2.plot(gL, cross, color="#8A4BBF", lw=2.5, label=r"$|E_l|^2|E_n|^2$ (cross-product)")

ax2.set_xlabel(r"Nonlinearity strength $\gamma L$", fontsize=12)
ax2.set_ylabel("Intensity (normalized)", fontsize=12)
ax2.set_title("(b) Output Intensities vs $\gamma L$", fontsize=14)
ax2.grid(True, alpha=0.3)
ax2.legend(loc='center left', bbox_to_anchor=(1, 0.5), frameon=False)

plt.tight_layout()
fig_fwm.savefig('fwm_overview_matplotlib.png', dpi=300, bbox_inches='tight')
plt.show()

# =============================================================================
# 2. Kerr Model Panels (Vertically Stacked)
# =============================================================================
fig_kerr, axes_kerr = plt.subplots(2, 1, figsize=(6, 10))

# Panel (c): SPM/XPM Phase
ax3 = axes_kerr[0]
gL_arr = np.linspace(0, 1.0, 100)
I_tot = np.linspace(0.5, 4.0, 100)
G, I_mat = np.meshgrid(gL_arr, I_tot)
phi = G * I_mat

c1 = ax3.contourf(G, I_mat, phi, levels=20, cmap="viridis")
ax3.contour(G, I_mat, phi, levels=6, colors='white', linewidths=0.5, alpha=0.7)
cbar1 = plt.colorbar(c1, ax=ax3)
cbar1.set_label(r"Phase $\phi$ (rad)", rotation=270, labelpad=15)

ax3.set_xlabel(r"Nonlinearity strength $\gamma L$", fontsize=12)
ax3.set_ylabel(r"Total Intensity $I_{\mathrm{tot}}$", fontsize=12)
ax3.set_title(r"(c) SPM/XPM Phase ($\phi \propto \gamma L \cdot I_{\mathrm{tot}}$)", fontsize=14)

# Panel (d): Cross-Intensity Feature Map
ax4 = axes_kerr[1]
N = 8
rng = np.random.default_rng(42)
I_modes = 1.0 + rng.normal(0, 0.3, N)**2
cross_mat = np.outer(I_modes, I_modes)
np.fill_diagonal(cross_mat, np.nan)

c2 = ax4.imshow(cross_mat, cmap="RdBu_r", origin='upper')
cbar2 = plt.colorbar(c2, ax=ax4)
cbar2.set_label(r"$|E_i|^2|E_j|^2$", rotation=270, labelpad=15)

for i in range(N):
    for j in range(N):
        if not np.isnan(cross_mat[i, j]):
            ax4.text(j, i, f"{cross_mat[i,j]:.2f}", ha='center', va='center', color='black', fontsize=8)

ax4.set_xticks(np.arange(N))
ax4.set_yticks(np.arange(N))
ax4.set_xticklabels([str(i+1) for i in range(N)])
ax4.set_yticklabels([str(i+1) for i in range(N)])
ax4.set_xlabel("Mode j", fontsize=12)
ax4.set_ylabel("Mode i", fontsize=12)
ax4.set_title(r"(d) Cross-Intensity Feature Map $\{|E_i|^2|E_j|^2\}$", fontsize=14)

plt.tight_layout()
fig_kerr.savefig('kerr_model_matplotlib.png', dpi=300, bbox_inches='tight')
plt.show()

